### ISSUE TITLE
Autocomplete HTML style attribute

### ISSUE THREAD

**Issue by bnaand** [atom/autocomplete-html#30] opened 2016-04-13 06:58 UTC
Should this package suggest content of style attribute in html files (CSS property names and values) or it is part of autocomplete-css or another package? 
Thanks

**Comment by 50Wliu** [comment] 2016-04-13 12:44
The problem is probably that the content of `style` isn't being marked as CSS - can you please file an issue on language-html instead?  Thanks.

**Closed by 50Wliu** 2016-04-13 12:44 UTC

**Comment by bnaand** [comment] 2016-04-13 13:08
OK, I will.
Thanks.
