### ISSUE TITLE
Some time appears all attributes permissible by a tag.

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/autocomplete-html#48] opened 2017-02-16 01:54 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Some time appears all attributes permissible by a tag, when i'm using the img tag, and try use align not appear on the autocomplete list, but after a while at the end of the img (<img src="" alt="" *here*>), sometimes appear the attributes.

### Steps to Reproduce

1. Open Atom
2. Create .html file.
3. try use some tag and use the attributes of the tags
4. use ctrl + space to open autocomplete.
5. look for the attribute.
6. not appear, nor writing.

**Expected behavior:** Appear a complete list of attributes.

**Actual behavior:** Appear a incomplete list of attributes

**Reproduces how often:** 90% of times.

### Versions

Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.82                                                                                                                                                                          
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.10.2

**Comment by 50Wliu** [comment] 2017-05-04 15:44
There have been significant improvements to autocomplete-html since this issue was opened, so I'm going to tentatively close this issue.  If you can still reproduce after Atom 1.18.0 is released, then please open another issue.

**Closed by 50Wliu** 2017-05-04 15:44 UTC
