### ISSUE TITLE
Autocomplete not working for html files

### ISSUE THREAD

**Issue by jaygala24** [atom/autocomplete-html#86] opened 2018-07-22 17:02 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jaygala24** [comment] 2018-07-22 17:02
Arguments to CompositeDisposable.add must have a .dispose() method
Hide Stack Trace
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\event-kit\lib\composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\event-kit\lib\composite-disposable.js:43:17)
    at Object.consumeProvider (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\autocomplete-plus\lib\main.js:89:27)
    at Object.consumeProvider_2 (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\autocomplete-plus\lib\main.js:62:23)
    at Provider.module.exports.Provider.provide (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\service-hub\lib\provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\service-hub\lib\service-hub.js:30:26)
    at Package.activateServices (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:397:75)
    at Package.activateNow (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:233:20)
    at measure (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package-manager.js:695:42)
    at packagesToEnable.forEach.name (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package-manager.js:440:51)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.config.onDidChange (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package-manager.js:440:30)
    at emitter.on (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\event-kit\lib\emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\event-kit\lib\emitter.js:156:34)
    at Config.emitChangeEvent (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\config.js:1226:62)
    at Config.setRawValue (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\config.js:1052:23)
    at Config.set (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\config.js:715:18)
    at Config.removeAtKeyPath (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\config.js:905:16)
    at Package.enable (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package.js:75:30)
    at PackageManager.enablePackage (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\src\package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\dell\AppData\Local\atom\app-1.28.2\resources\app\node_modules\settings-view\lib\package-card.js:362:31)

This is the error

**Comment by rsese** [comment] 2018-07-24 05:14
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/autocomplete-plus/issues/851 so you can subscribe there for updates if you'd like.  If you have specific steps to reproduce, please let us know in https://github.com/atom/autocomplete-plus/issues/851.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-07-24 05:14 UTC
