### ISSUE TITLE
Class Quotes Not Ignored

### ISSUE THREAD

**Issue by someyoungideas** [atom/autocomplete-html#36] opened 2016-06-22 02:32 UTC
When using autocomplete for the `class` attribute it correctly adds the quotes. Is there a way to escape outside the quotes? If not the issue I am running into is I do not know of a way to escape the quotes, so when I type the quotes is adds one instead of recognizing that keystroke as the closing quotes and allowing me to escape. So this happens, `<div class="someclass"">`

**Comment by 50Wliu** [comment] 2017-04-28 03:17
You can <kbd>tab</kbd> out of the quotes.  This is duplicate of https://github.com/atom/bracket-matcher/issues/28 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2017-04-28 03:17 UTC
