### ISSUE TITLE
Close previous tag when type </

### ISSUE THREAD

**Issue by kritsky** [atom/autocomplete-html#9] opened 2015-07-15 07:43 UTC
Is there any way to do that?

**Comment by mnquintana** [comment] 2015-07-15 11:04
You can close a tag in an HTML document with <kbd>Cmd-Alt-.</kbd> (or <kbd>Ctrl-Alt-.</kbd> on Windows and Linux) – does that about cover what you're looking for?

**Comment by kritsky** [comment] 2015-07-15 12:35
Yes. But it is better to type <kbd></</kbd> like in sublime. No need to <kbd>cmd+alt+.</kbd> just <kbd></</kbd> and that's it. Simplier

**Comment by mnquintana** [comment] 2015-07-15 13:23
This is actually a duplicate of https://github.com/atom/language-html/issues/63 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-15 13:23 UTC

**Comment by kritsky** [comment] 2015-07-15 14:03
thank you
